name: pr_build

on:
  push:
    branches:
      - "feature/A-2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64/v8]
    steps:
      -
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-13
      -
        name: Install tools
        run: |
          export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get upgrade -y && apt-get install -y build-essential curl cmake
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform }}
          restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.platform }}
      -
        name: Build Rust
        run: |
          rustup default nightly-2022-01-13
          rustup component add rustfmt
          cargo build --release
          cp target/release/firm-wallet-service dockerfiles/firm-wallet-service/
          cp target/release/firm-wallet-gateway dockerfiles/firm-wallet-gateway/
          cp firm-wallet-gateway/.env dockerfiles/firm-wallet-gateway/.env
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: feyman2019
          password: dckr_pat_6CmmtEh1bfUaRgOmtEXFa4cYpwo
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Show current directory
        run: |
          echo "Show current Dir"
          pwd
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/firm-wallet-service
          platforms: ${{ matrix.platform }}
          file: ./dockerfiles/firm-wallet-service/Dockerfile
          push: true
          tags: feyman2019/auticuro_2:latest