name: pr_build

on:
  push:
    branches:
      - "feature/A-2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: feyman2019
          password: dckr_pat_6CmmtEh1bfUaRgOmtEXFa4cYpwo
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Show current directory
        run: |
          echo "Show current Dir"
          pwd
      -
        name: Show customized directory
        working-directory: ./dockerfiles
        run: |
          echo "Show customized Dir"
          pwd
      -
        name: Build Rust
        run: |
#          cargo build --release
#          mv target/release/firm-wallet-service dockerfiles/firm-wallet-service/
#          mv target/release/firm-wallet-gateway dockerfiles/firm-wallet-gateway/
          cp firm-wallet-gateway/.env dockerfiles/firm-wallet-gateway/.env
      -
        name: Build and push
        uses: docker/build-push-action@v4
        working-directory: ./dockerfiles/firm-wallet-service
        with:
          context: .
          file: ./dockerfiles/firm-wallet-service/Dockerfile
          push: true
          tags: feyman2019/auticuro:latest
